// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofkzxnmldmyxhjxgvukb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ma3p4bm1sZG15eGhqeGd2dWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDE3ODUsImV4cCI6MjA1OTI3Nzc4NX0.vBnjjTvLsWAz7kLCX98CewlYRZus-wjv-ZZNNmu2JP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);